### ISSUE TITLE
config parameters are not loaded from json

### ISSUE THREAD

**Issue by makevin23** [rashad101/SGPT-SPARQL-query-generation#4]
Hi, I have some problem while training this model.
When I run 
```bash
python -m torch.distributed.launch train.py --dataset qald9
```
on my server with 2 GPUs, it didn't load the parameters from the `params.json` file and train 70 epochs, but it just didn't start training. 
I assume `train.py` is not able to read `paramas.json` and take the default epoch -1. 
Can you fix this problem?

**Comment by rashad101** [comment]
Hi, there was an error in the training and dataset loading script for which the training script was throwing an error. Now that issue is resolved. Unfortunately, I do not have access to multiple GPU for this task unfortunately. Could you please try again with a single GPU (```python train.py --dataset qald9```)?

Thanks for your understanding
