### ISSUE TITLE
When evaluating the model I encounter an error can you help me

### ISSUE THREAD

**Issue by b67822** [rashad101/SGPT-SPARQL-query-generation#8]
<img width="520" alt="Screenshot 2024-03-21 064112" src="https://github.com/rashad101/SGPT-SPARQL-query-generation/assets/91271446/8fccf51e-e299-45a9-ac69-afe4a21f3c7f">
I face this error when evaluating the model can you please help me.

Thank you.

**Comment by rashad101** [comment]
Hi,
the error was caused by not training the model enough and doing the evaluation. While training add a suiitable epoch parameter (prefereablly around 40 or more for the benchmark dataset used in this paper). E.g., on `train.py --dataset lcquad2 --epochs 40` I have updated the README.md please refer to the updated commandes mentioned in README.md

Best regards,
Rashad
